server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
    profiles:
      active: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
#      data: classpath:static/assets/initDatabse.sql
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
